#!/usr/bin/env python3
"""
Re-derive `transcript_lines` for every entity by scanning the episode
transcript files and matching against `name` + `alt_names`. Updates
`data/episodes/ep*.json` in place.

Why: the initial `transcript_lines` were generated by hand / one-off LLM
passes and miss a lot of mentions. A deterministic word-boundary scan over
the actual transcript catches everything the names + aliases will catch,
and it's reproducible — re-run after editing aliases to refresh.

After running this, run `python data/merge.py` to roll the per-episode
edits into the unified `entities.json` files the frontend reads.

Usage:
    python data/build_transcript_lines.py                  # all episodes
    python data/build_transcript_lines.py --episodes 10    # just ep 10
    python data/build_transcript_lines.py --dry-run        # report only

What is matched:
- Each entity's `name` and any `alt_names` are turned into case-insensitive
  patterns with letter-boundary anchors (so "Hera" doesn't match "Heraclius").
- Patterns shorter than 3 characters are skipped — too noisy.
- When two entities both match the same span on a line, the entity whose
  matching pattern is LONGER wins and shadows the shorter one (e.g.,
  "Heraclius the Elder" suppresses "Heraclius" on lines that contain the
  longer phrase). Same-entity overlaps don't shadow each other.

Range merging: consecutive hit lines within MERGE_GAP of each other are
collapsed into a single [start, end] range.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Iterable

# Lines within this many of each other get merged into one range. Smaller
# values produce more, finer-grained ranges — important because the UI fires
# a re-pulse only when the active anchor *changes*, so a long entity like
# Heraclius sitting in one giant range never re-pulses on subsequent
# mentions. Two-line gaps keep adjacent prose together while letting nearby
# but distinct mentions stay separate so each one triggers a fresh pulse.
MERGE_GAP = 2

# Single- and two-letter aliases produce too many false positives.
MIN_PATTERN_LEN = 3

ROOT = Path(__file__).resolve().parent
EPISODES_DIR = ROOT / "episodes"
TRANSCRIPTS_DIR = ROOT.parent / "transcripts"


# ---------- transcript loading ----------

def transcript_path_for_ep(ep_num: int) -> Path:
    """Find a transcript file like '10 - Episode 10 - <title>.txt'."""
    candidates = list(TRANSCRIPTS_DIR.glob(f"{ep_num:02d} - Episode {ep_num} - *.txt"))
    if not candidates:
        candidates = list(TRANSCRIPTS_DIR.glob(f"{ep_num} - Episode {ep_num} - *.txt"))
    if not candidates:
        raise FileNotFoundError(f"No transcript file for episode {ep_num} in {TRANSCRIPTS_DIR}")
    if len(candidates) > 1:
        raise RuntimeError(f"Multiple transcripts match ep {ep_num}: {candidates}")
    return candidates[0]


def load_transcript(ep_num: int) -> list[str]:
    return transcript_path_for_ep(ep_num).read_text(encoding="utf-8").splitlines()


# ---------- pattern building ----------

# Roman numerals (regnal suffixes) that we strip to derive a bare-name
# fallback pattern. "Justinian I" -> bare "Justinian". Capped at XII because
# higher Roman numerals don't appear in this dataset.
_ROMAN_SUFFIX_RE = re.compile(
    r"\s+(?:I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)$",
    re.IGNORECASE,
)
# "the X" descriptors. We DON'T strip these by default — "Constantine the
# Great" -> "Constantine" would conflict with all the other Constantines.
# Kept for reference if we want to opt in per-entity later.

# Words that signal we've left the proper-noun head of an event name. The
# first preposition / verb-ish word ends the "key phrase" used as a fallback
# pattern for events with descriptive labels. Kept short because false
# friends ("of" in "Bishop of Rome") are far rarer in event names than in
# free text.
_EVENT_PHRASE_STOPWORDS = {
    "of", "to", "in", "at", "on", "by", "for", "with", "from",
    "against", "as", "and", "or", "but", "the", "a", "an",
}

# Generic single-word phrases that produce too many false positives when
# used as bare patterns ("Coronation", "Council", "Battle", etc. show up
# constantly).
_TOO_GENERIC_SINGLE_WORDS = {
    "battle", "siege", "death", "fall", "rise", "council", "coronation",
    "deposition", "marriage", "mission", "conquest", "campaign",
    "invasion", "revolt", "victory", "defeat", "execution", "murder",
    "burning", "founding", "foundation", "construction", "publication",
    "dedication", "establishment", "great", "elder", "younger", "first",
    "second", "third", "saint", "pope", "patriarch", "emperor", "empress",
    "king", "queen", "prince", "princess", "general", "city", "war",
    "rebellion", "raid",
}


def _bare_name_for_regnal(name: str) -> str | None:
    """Strip a trailing Roman numeral. 'Justinian I' -> 'Justinian'."""
    stripped = _ROMAN_SUFFIX_RE.sub("", name).strip()
    if stripped == name or len(stripped) < MIN_PATTERN_LEN:
        return None
    return stripped


def _event_key_phrase(name: str) -> str | None:
    """Pull the leading proper-noun phrase out of an event name.

    'True Cross Returned to Jerusalem' -> 'True Cross'
    'Lombard Invasion of Italy'        -> 'Lombard Invasion'
    'Coronation of Heraclius'          -> None (single generic word)
    'Battle of Manzikert'              -> 'Manzikert' (post-"of" fallback)

    Strategy: take title-case content words until we hit a stopword OR a
    verb-ish word (-ed / -ing). Drop single-word generics. If the leading
    head is purely generic ("Battle", "Death", "Coronation"), try the tail
    after the first preposition — that's where the proper noun usually
    lives ("Battle of Manzikert" -> "Manzikert").
    """

    def take_content_words(words: list[str]) -> list[str]:
        keep: list[str] = []
        for w in words:
            wl = w.lower()
            if wl in _EVENT_PHRASE_STOPWORDS:
                break
            # Past-tense / progressive heuristic: a content word ending in
            # -ed or -ing (long enough not to be "fed" / "led" / "sing")
            # signals we've moved from the noun phrase head into a verb,
            # so stop. Lets "True Cross Returned to Jerusalem" yield just
            # "True Cross".
            if (wl.endswith("ed") or wl.endswith("ing")) and len(wl) > 4:
                break
            keep.append(w)
        return keep

    def usable(keep: list[str]) -> str | None:
        if not keep:
            return None
        phrase = " ".join(keep)
        if len(phrase) < MIN_PATTERN_LEN:
            return None
        if len(keep) == 1 and keep[0].lower() in _TOO_GENERIC_SINGLE_WORDS:
            return None
        if phrase == name:
            return None
        return phrase

    parts = name.split()
    head = take_content_words(parts)
    head_phrase = usable(head)
    if head_phrase:
        return head_phrase

    # Head was generic ("Battle of X", "Death of X", "Coronation of X"); try
    # the words after the first preposition.
    for i, w in enumerate(parts):
        if w.lower() in _EVENT_PHRASE_STOPWORDS and i < len(parts) - 1:
            tail = take_content_words(parts[i + 1 :])
            tail_phrase = usable(tail)
            if tail_phrase:
                return tail_phrase
            break

    return None


def build_patterns_for_entity(
    entity: dict,
) -> list[tuple[re.Pattern, str, str]]:
    """Return [(compiled_regex, raw_pattern_string, kind), ...] for this entity.

    `kind` is one of:
      - "full":     name or alt_name (highest priority, claims wins ties)
      - "fallback": derived bare-name / key-phrase (only attributed if the
                    entity already has at least one full-name match or
                    pre-existing line range in the same episode — this
                    disambiguates ambiguous bares like "Justinian" between
                    Justinian I / Justinian II by deferring to the entity
                    that's already shown to be discussed.)

    Patterns use letter-boundary lookarounds — `\\b` is unreliable when the
    name itself contains punctuation or non-word chars.
    """
    out: list[tuple[re.Pattern, str, str]] = []
    seen: set[str] = set()

    def add(raw: str, kind: str) -> None:
        s = raw.strip()
        if len(s) < MIN_PATTERN_LEN:
            return
        key = s.lower()
        if key in seen:
            return
        seen.add(key)
        pat = re.compile(
            r"(?<![A-Za-z])" + re.escape(s) + r"(?![A-Za-z])",
            re.IGNORECASE,
        )
        out.append((pat, s, kind))

    name = (entity.get("name") or "").strip()
    if name:
        add(name, "full")
    for alt in entity.get("alt_names") or []:
        add(alt, "full")

    # Fallback patterns — bare regnal name for people, key phrase for events.
    if entity.get("kind") == "person" or "reign_start" in entity or "birth_year" in entity:
        bare = _bare_name_for_regnal(name)
        if bare:
            add(bare, "fallback")
    if entity.get("kind") == "event" or "year" in entity:
        # Heuristic kind detection: per-episode files don't carry a `kind`
        # field, so we sniff via fields. Both branches are fine to run for
        # the same entity since `add()` dedupes.
        phrase = _event_key_phrase(name)
        if phrase:
            add(phrase, "fallback")

    return out


# ---------- per-episode scan ----------

def find_hits(
    entities_with_patterns: list[tuple[str, list[tuple[re.Pattern, str, str]]]],
    lines: list[str],
    existing_lines_per_entity: dict[str, set[int]],
) -> dict[str, list[int]]:
    """Returns entity_id -> sorted list of 1-indexed line numbers.

    Two passes:

      Pass 1 (full): direct `name`/`alt_names` matches. Per-line, longer
        pattern matches shadow shorter ones from *different* entities that
        overlap their span — "Heraclius the Elder" claiming [0,19]
        suppresses "Heraclius" (different entity) at [0,9] on the same
        line. Same-entity overlaps don't shadow.

      Pass 2 (fallback): bare-name / event-key-phrase matches. These are
        only attributed to entities that already have *evidence* in this
        episode — either a full-name hit from pass 1, or non-empty
        pre-existing transcript_lines. This stops "Justinian" in an
        episode that mentions Justinian I once (full name) and never
        Justinian II from being attributed to Justinian II.
        Among multiple eligible entities, the one with the most existing
        evidence wins (ties broken deterministically by id).
    """
    hits: dict[str, set[int]] = {}

    # ---- Pass 1: full-name matches ----
    for line_num, line in enumerate(lines, start=1):
        line_matches: list[tuple[str, int, int, int]] = []
        for entity_id, patterns in entities_with_patterns:
            for pat, raw, kind in patterns:
                if kind != "full":
                    continue
                for m in pat.finditer(line):
                    line_matches.append((entity_id, m.start(), m.end(), len(raw)))
        if not line_matches:
            continue
        line_matches.sort(key=lambda t: (-t[3], t[0], t[1]))
        claimed: list[tuple[int, int, str]] = []
        for entity_id, s, e, _plen in line_matches:
            shadowed = False
            for cs, ce, ceid in claimed:
                if ceid == entity_id:
                    continue
                if s < ce and e > cs:
                    shadowed = True
                    break
            if shadowed:
                continue
            claimed.append((s, e, entity_id))
            hits.setdefault(entity_id, set()).add(line_num)

    # ---- Pass 2: fallback patterns, eligible entities only ----
    # An entity is eligible if it has any pass-1 hits OR any pre-existing
    # transcript_lines in this episode (from the curated dataset).
    eligible: dict[str, int] = {}  # entity_id -> evidence weight
    for entity_id, _patterns in entities_with_patterns:
        evidence = len(hits.get(entity_id, ())) + len(
            existing_lines_per_entity.get(entity_id, ())
        )
        if evidence > 0:
            eligible[entity_id] = evidence

    for line_num, line in enumerate(lines, start=1):
        # Collect fallback matches across all entities at this line.
        bare_matches: list[tuple[str, int, int, int]] = []
        for entity_id, patterns in entities_with_patterns:
            if entity_id not in eligible:
                continue
            for pat, raw, kind in patterns:
                if kind != "fallback":
                    continue
                for m in pat.finditer(line):
                    bare_matches.append((entity_id, m.start(), m.end(), len(raw)))
        if not bare_matches:
            continue
        # If this line already has a *full* claim by some entity, suppress
        # any overlapping fallback claim by a *different* entity. This
        # prevents "Justinian" in "Justinian I" from being doubly attributed
        # to Justinian II via fallback.
        full_claims_on_line: list[tuple[int, int, str]] = []
        for entity_id, patterns in entities_with_patterns:
            for pat, raw, kind in patterns:
                if kind != "full":
                    continue
                for m in pat.finditer(line):
                    full_claims_on_line.append((m.start(), m.end(), entity_id))
        # Group bare matches by overlap with full claims.
        eligible_bare = []
        for entity_id, s, e, plen in bare_matches:
            shadowed = False
            for cs, ce, ceid in full_claims_on_line:
                if ceid == entity_id:
                    continue
                if s < ce and e > cs:
                    shadowed = True
                    break
            if not shadowed:
                eligible_bare.append((entity_id, s, e, plen))
        if not eligible_bare:
            continue
        # Group bare matches by literal span. Multiple entities producing
        # the SAME bare token (all Justinians -> "Justinian") collapse to
        # one winner per span — the highest-evidence eligible entity. But
        # bare matches at *different* spans on the same line (e.g.
        # "Justinian" early in the line and "Greek" later) are credited
        # independently to their respective entities.
        from collections import defaultdict
        by_span: dict[tuple[int, int], list[str]] = defaultdict(list)
        for entity_id, s, e, _plen in eligible_bare:
            by_span[(s, e)].append(entity_id)
        for span, candidates in by_span.items():
            if len(candidates) == 1:
                winner_id = candidates[0]
            else:
                # Highest evidence wins; tie-break alphabetical.
                winner_id = max(candidates, key=lambda eid: (eligible[eid], -ord(eid[0])))
            hits.setdefault(winner_id, set()).add(line_num)

    return {eid: sorted(s) for eid, s in hits.items()}


def group_into_ranges(line_nums: Iterable[int], merge_gap: int) -> list[list[int]]:
    """Collapse a sorted list of line numbers into [start, end] ranges,
    merging hits within `merge_gap` of each other."""
    out: list[list[int]] = []
    for n in line_nums:
        if out and n - out[-1][1] <= merge_gap:
            out[-1][1] = n
        else:
            out.append([n, n])
    return out


# ---------- main per-episode driver ----------

def process_episode(
    ep_path: Path, dry_run: bool = False, verbose: bool = False
) -> dict:
    data = json.loads(ep_path.read_text(encoding="utf-8"))
    ep_num = data["episode"]

    try:
        lines = load_transcript(ep_num)
    except FileNotFoundError as e:
        print(f"  ! ep{ep_num:02d}: {e}", file=sys.stderr)
        return {"ep": ep_num, "skipped": "no transcript"}

    # Flatten people/places/events into one list. We need the kind too so
    # build_patterns_for_entity can decide which fallback to generate.
    entities_with_patterns: list[
        tuple[str, list[tuple[re.Pattern, str, str]]]
    ] = []
    entity_index: dict[str, dict] = {}
    existing_lines_per_entity: dict[str, set[int]] = {}
    kind_singular = {"people": "person", "places": "place", "events": "event"}
    for kind in ("people", "places", "events"):
        for entity in data.get(kind, []):
            entity = {**entity, "kind": kind_singular[kind]}
            patterns = build_patterns_for_entity(entity)
            entities_with_patterns.append((entity["id"], patterns))
            entity_index[entity["id"]] = entity
            existing: set[int] = set()
            for r in entity.get("transcript_lines") or []:
                for n in range(r[0], r[1] + 1):
                    existing.add(n)
            if existing:
                existing_lines_per_entity[entity["id"]] = existing

    hit_lines = find_hits(entities_with_patterns, lines, existing_lines_per_entity)

    # Replace transcript_lines with the script's matches when we found any
    # — the script's ranges are finer-grained than the original curated
    # ones (each cluster of mentions becomes its own [start,end] pair),
    # which matters because the UI re-pulses only when the active anchor
    # transitions. If the script found 0 matches (typical of events whose
    # *names* are descriptive labels — "Overthrow of Phocas" never appears
    # literally), keep the curated ranges so we don't silently drop them.
    changed = grew = 0
    new_match_count = 0
    # Look up the original entry by id (we mutated `entity` to add `kind`,
    # but the file we'll write back uses the per-kind lists.)
    for kind in ("people", "places", "events"):
        for entity in data.get(kind, []):
            entity_id = entity["id"]
            old_ranges = entity.get("transcript_lines") or []
            script_lines = hit_lines.get(entity_id, [])

            if script_lines:
                new_ranges = group_into_ranges(script_lines, MERGE_GAP)
            else:
                new_ranges = [list(r) for r in old_ranges]

            if [list(r) for r in old_ranges] != new_ranges:
                changed += 1
                old_count = sum(r[1] - r[0] + 1 for r in old_ranges)
                new_count = sum(r[1] - r[0] + 1 for r in new_ranges)
                if new_count > old_count:
                    grew += 1
                if verbose:
                    print(
                        f"    {entity_id}: {len(old_ranges)} ranges ({old_count} lines) "
                        f"-> {len(new_ranges)} ranges ({new_count} lines)"
                    )
                entity["transcript_lines"] = new_ranges
            new_match_count += sum(r[1] - r[0] + 1 for r in new_ranges)

    if not dry_run:
        ep_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    return {
        "ep": ep_num,
        "transcript_lines": len(lines),
        "entities_scanned": len(entities_with_patterns),
        "entities_with_hits": len(hit_lines),
        "matched_lines_total": new_match_count,
        "changed": changed,
        "grew": grew,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="don't write changes")
    ap.add_argument("--episodes", help="comma-separated episode numbers")
    ap.add_argument("-v", "--verbose", action="store_true", help="print per-entity diffs")
    args = ap.parse_args()

    wanted: set[int] | None = None
    if args.episodes:
        wanted = {int(x.strip()) for x in args.episodes.split(",") if x.strip()}

    paths = sorted(EPISODES_DIR.glob("ep*.json"))
    total = {"changed": 0, "grew": 0, "matched_lines_total": 0}
    for p in paths:
        ep_num = int(p.stem.removeprefix("ep"))
        if wanted is not None and ep_num not in wanted:
            continue
        if args.verbose:
            print(f"ep{ep_num:02d}:")
        stats = process_episode(p, dry_run=args.dry_run, verbose=args.verbose)
        if "skipped" in stats:
            continue
        print(
            f"ep{ep_num:02d}: {stats['matched_lines_total']:4d} total matched lines  "
            f"({stats['entities_with_hits']}/{stats['entities_scanned']} entities)  "
            f"{stats['changed']} changed ({stats['grew']} gained new lines)"
        )
        total["changed"] += stats["changed"]
        total["grew"] += stats["grew"]
        total["matched_lines_total"] += stats["matched_lines_total"]

    print()
    print(
        f"TOTAL: {total['matched_lines_total']} matched lines, "
        f"{total['changed']} entities changed ({total['grew']} gained new lines)"
    )
    if args.dry_run:
        print("(dry-run — no files written)")
    else:
        print("\nNext: run `python data/merge.py` to roll into entities.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
